name: Clang Formatter
on: workflow_dispatch
jobs:
  Job:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install clang-format
        run: sudo apt-get install clang-format -y

      - name: Formatting files
        run: chmod +x ./format.sh && ./format.sh

      - name: Verify Formatting
        run: git status --short

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: formattedFiles
          path: ./project
          if-no-files-found: error
