name: Testing
on:
  push:
    branches: main
    paths-ignore:
      - '.github/workflows/clang-formatter.yml'
      - 'project/.clang-format'
      - 'LICENSE'
      - 'README.md'
      - 'haxelib.json'
      - 'hxformat.json'
  workflow_dispatch:
jobs:
  Job:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        sample: [albedo_pcb, basic]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install libudev and socat
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y libudev-dev socat

      - name: Create virtual serial devices
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          PTY0=$(socat -d -d PTY,raw,echo=0 PTY,raw,echo=0 2>&1 | grep -o '/dev/pts/[0-9]*' | head -n 1)
          PTY1=$(socat -d -d PTY,raw,echo=0 PTY,raw,echo=0 2>&1 | grep -o '/dev/pts/[0-9]*' | head -n 1)
          echo "PTY0: $PTY0"
          echo "PTY1: $PTY1"
          socat -d -d $PTY0 $PTY1 &

      - name: Install Dependencies
        run: |
          haxelib install hxcpp --quiet
          haxelib dev hxserial_api .

      - name: Build Unix
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        run: cd samples/${{matrix.sample}} && haxe build-unix.hxml

      - name: Build Windows
        if: startsWith(matrix.os, 'windows')
        run: cd samples/${{matrix.sample}} && haxe build-win.hxml
  
